version: "3"
services:
  nginx:
    container_name: docker_nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - client

  client:
    container_name: docker_client
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      SERVER_URL: http://localhost:3000
